
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 08 19:14:05 CEST 2022
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int r_true = 29;
  public static final int r_null = 35;
  public static final int llcierre = 21;
  public static final int mod = 9;
  public static final int r_del = 55;
  public static final int r_false = 30;
  public static final int flecha = 22;
  public static final int r_real = 27;
  public static final int asig = 4;
  public static final int blt = 10;
  public static final int r_else = 39;
  public static final int pap = 16;
  public static final int coma = 23;
  public static final int r_read = 50;
  public static final int r_var = 53;
  public static final int r_then = 38;
  public static final int r_proc = 36;
  public static final int ble = 12;
  public static final int r_or = 32;
  public static final int r_pointer = 48;
  public static final int r_string = 34;
  public static final int r_array = 46;
  public static final int lit_int = 59;
  public static final int r_if = 37;
  public static final int menos = 6;
  public static final int r_write = 51;
  public static final int EOF = 0;
  public static final int r_of = 47;
  public static final int beq = 14;
  public static final int mas = 5;
  public static final int sep_prog = 2;
  public static final int r_int = 26;
  public static final int error = 1;
  public static final int pto_coma = 3;
  public static final int lit_cad = 57;
  public static final int r_endwhile = 43;
  public static final int ccierre = 19;
  public static final int por = 7;
  public static final int r_not = 33;
  public static final int punto = 24;
  public static final int r_and = 31;
  public static final int pcierre = 17;
  public static final int id = 58;
  public static final int bne = 15;
  public static final int cap = 18;
  public static final int r_nl = 52;
  public static final int et = 25;
  public static final int bgt = 11;
  public static final int r_type = 54;
  public static final int r_new = 49;
  public static final int r_bool = 28;
  public static final int r_call = 44;
  public static final int lit_real = 56;
  public static final int r_record = 45;
  public static final int r_endif = 40;
  public static final int div = 8;
  public static final int r_while = 41;
  public static final int bge = 13;
  public static final int r_do = 42;
  public static final int llap = 20;
}

