/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExp = 6;
  int AllowedCharacters = 7;
  int r_int = 10;
  int r_real = 11;
  int r_bool = 12;
  int r_true = 13;
  int r_false = 14;
  int r_and = 15;
  int r_or = 16;
  int r_not = 17;
  int r_string = 18;
  int r_null = 19;
  int r_proc = 20;
  int r_if = 21;
  int r_then = 22;
  int r_else = 23;
  int r_endif = 24;
  int r_while = 25;
  int r_do = 26;
  int r_endwhile = 27;
  int r_call = 28;
  int r_record = 29;
  int r_array = 30;
  int r_of = 31;
  int r_pointer = 32;
  int r_new = 33;
  int r_del = 34;
  int r_read = 35;
  int r_write = 36;
  int r_nl = 37;
  int r_var = 38;
  int r_type = 39;
  int identificador = 40;
  int numeroEntero = 41;
  int numeroReal = 42;
  int cadena = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExp>",
    "<AllowedCharacters>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"string\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"del\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<identificador>",
    "<numeroEntero>",
    "<numeroReal>",
    "<cadena>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
