package alex;

public enum ClaseLexica {
 SEP_PROG, PTO_COMA, R_INT, R_REAL, R_BOOL, ASIG, R_TRUE, R_FALSE,
 MAS, MENOS, POR, DIV, R_AND, R_OR, R_NOT, BLT, BGT, BGE, BLE,
 BEQ, BNE, PAP, PCIERRE, ID, LIT_INT, LIT_REAL, EOF
}
