package alex;

public enum ClaseLexica {
 SEP_PROG, PTO_COMA, R_INT, R_REAL, R_BOOL, ASIG, R_TRUE, R_FALSE,
 MAS, MENOS, POR, DIV, NEG, R_AND, R_OR, R_NOT, BLT, BGT, BGE,
 EQ, NEQ, PAP, PCIERRE, MOD, CCIERRE, CAP, LLCIERRE, LLAP, FLECHA,
 COMA, PUNTO, ET, R_STRING, R_NULL, R_PROC, R_IF, R_THEN, R_ELSE, 
 R_ENDIF, R_WHILE, R_DO, R_ENDWHILE, R_CALL, R_RECORD, R_ARRAY, 
 R_OF, R_POINTER, R_NEW, R_DEL, R_READ, R_WRITE, R_NL, R_VAR, R_TYPE
 ID, LIT_INT, LIT_REAL
}
